### ISSUE TITLE
package.json dependencies should be empty 

### ISSUE THREAD

**Issue by tkrotoff** [enaukkarinen/modest-tsc-ng1-boilerplate#2]
[package.json](https://github.com/enaukkarinen/modest-tsc-ng1-boilerplate/blob/0b5950a/package.json#L8):

``` JSON
  "dependencies": {
    "almond": "^0.3.2",
    "angular": "^1.5.3",
    "angular-route": "^1.5.3",
    "bootstrap": "^3.3.6",
    "jquery": "^2.2.3"
  }
```

This package does not depend on anything since everything is already bundled:
- dev/js/lib.js already contains almond, AngularJS, jQuery
- dev/css/lib.css already contains Bootstrap

Btw, the [package name](https://github.com/enaukkarinen/modest-tsc-ng1-boilerplate/blob/0b5950a/package.json#L2) can be changed from "gulp-tsc-boilerplate" to "modest-tsc-ng1-boilerplate" :)

**Comment by enaukkarinen** [comment]
Right you are. Moved these to devDependencies. Thanks mate.
